apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-auth
  namespace: circleguard-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-gateway
  namespace: circleguard-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-form
  namespace: circleguard-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-promotion
  namespace: circleguard-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-notification
  namespace: circleguard-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-identity
  namespace: circleguard-dev
