apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

      - job_name: 'circleguard-auth'
        static_configs:
          - targets: ['circleguard-auth-service.circleguard-dev:8180']
        metrics_path: /actuator/prometheus

      - job_name: 'circleguard-gateway'
        static_configs:
          - targets: ['circleguard-gateway-service.circleguard-dev:8087']
        metrics_path: /actuator/prometheus

      - job_name: 'circleguard-form'
        static_configs:
          - targets: ['circleguard-form-service.circleguard-dev:8086']
        metrics_path: /actuator/prometheus

      - job_name: 'circleguard-promotion'
        static_configs:
          - targets: ['circleguard-promotion-service.circleguard-dev:8088']
        metrics_path: /actuator/prometheus

      - job_name: 'circleguard-notification'
        static_configs:
          - targets: ['circleguard-notification-service.circleguard-dev:8082']
        metrics_path: /actuator/prometheus

      - job_name: 'circleguard-identity'
        static_configs:
          - targets: ['circleguard-identity-service.circleguard-dev:8083']
        metrics_path: /actuator/prometheus
